import { Activity, Archive, ArrowLeft, BadgeCheck, Bell, Camera, CheckCircle2, ClipboardList, Eye, FolderKanban, Heart, ImagePlus, KeyRound, LoaderCircle, LockKeyhole, Mail, NotebookTabs, ShieldCheck, SlidersHorizontal, Trash2, UserRound, UsersRound } from "lucide-react";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

function formatDate(value: Date | string | null | undefined, withTime = false) {
  if (!value) return "尚無紀錄";
  return new Date(value).toLocaleString("zh-TW", withTime ? { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" } : { year: "numeric", month: "long", day: "numeric" });
}

function statusLabel(status: string) {
  return ({ active: "啟用中", pending_activation: "待啟用", inactive: "已停用", alumni: "校友", registered: "已報名", waitlisted: "候補中", cancelled: "已取消", attended: "已出席", absent: "缺席", todo: "待處理", in_progress: "進行中", blocked: "受阻", completed: "已完成", submitted: "已送出", document_review: "書面審查", returned: "待補件", interview_scheduled: "已安排面試", interview_completed: "面試完成", approved: "已核准", waitlisted_application: "候補", rejected: "未錄取", activation_pending: "待啟用", withdrawn: "已撤回", expired: "已逾期" } as Record<string, string>)[status] || status;
}

function auditLabel(action: string) {
  return ({ "personal.profile_updated": "更新個人資料", "personal.preferences_updated": "更新個人偏好", "personal.avatar_uploaded": "更新個人頭像", "personal.avatar_removed": "移除個人頭像", "personal.password_changed": "變更登入密碼", "resource.download_requested": "下載資源", "resource.open_requested": "開啟資源", "event.registration_cancelled": "取消活動報名", "project.task_status_updated_by_assignee": "更新我的任務狀態", "account.admin_profile_updated": "管理者更新帳號資料", "account.admin_deactivated": "管理者停用帳號", "account.admin_status_updated": "管理者調整帳號狀態", "account.admin_activation_reset": "管理者重設啟用流程" } as Record<string, string>)[action] || "帳號或權限異動";
}

export default function PersonalCenterPage() {
  const { user, isAuthenticated, logout } = useAuth();
  const utils = trpc.useUtils();
  const summary = trpc.personal.summary.useQuery(undefined, { enabled: isAuthenticated });
  const myTasks = trpc.workspace.projectWork.mine.useQuery(undefined, { enabled: isAuthenticated });
  const [profile, setProfile] = useState({ name: "", grade: "", contact: "" });
  const [preferences, setPreferences] = useState({ reducedMotion: false, inAppNotifications: true, emailNotifications: false, resourceHistoryVisible: true });
  const updateProfile = trpc.personal.updateProfile.useMutation({ onSuccess: async () => { toast.success("個人資料已更新。"); await utils.personal.summary.invalidate(); }, onError: error => toast.error(error.message) });
  const updatePreferences = trpc.personal.updatePreferences.useMutation({ onSuccess: async () => { toast.success("個人偏好已儲存。"); await utils.personal.summary.invalidate(); }, onError: error => toast.error(error.message) });
  const uploadAvatar = trpc.personal.uploadAvatar.useMutation({ onSuccess: async () => { toast.success("個人頭像已更新。"); await utils.personal.summary.invalidate(); }, onError: error => toast.error(error.message) });
  const removeAvatar = trpc.personal.removeAvatar.useMutation({ onSuccess: async () => { toast.success("個人頭像已移除。"); await utils.personal.summary.invalidate(); }, onError: error => toast.error(error.message) });
  const changePassword = trpc.personal.changePassword.useMutation({ onSuccess: () => toast.success("密碼已更新；請妥善保管新的登入憑證。"), onError: error => toast.error(error.message) });
  const markNotificationRead = trpc.personal.markNotificationRead.useMutation({ onSuccess: () => void utils.personal.summary.invalidate(), onError: error => toast.error(error.message) });
  const archiveNotification = trpc.personal.archiveNotification.useMutation({ onSuccess: () => void utils.personal.summary.invalidate(), onError: error => toast.error(error.message) });
  const cancelRegistration = trpc.content.events.cancelRegistration.useMutation({ onSuccess: () => { toast.success("活動報名已取消。"), utils.personal.summary.invalidate(), utils.content.events.listForMember.invalidate(), utils.content.events.myRegistrationStatuses.invalidate(); }, onError: error => toast.error(error.message) });

  useEffect(() => {
    if (!summary.data) return;
    setProfile({ name: summary.data.user.name || "", grade: summary.data.user.grade || "", contact: summary.data.user.contact || "" });
    setPreferences({ reducedMotion: summary.data.preferences.reducedMotion, inAppNotifications: summary.data.preferences.inAppNotifications, emailNotifications: summary.data.preferences.emailNotifications, resourceHistoryVisible: summary.data.preferences.resourceHistoryVisible });
  }, [summary.data]);
  useEffect(() => {
    try { localStorage.setItem("fjubac-user-reduced-motion", preferences.reducedMotion ? "true" : "false"); } catch { /* 瀏覽器可能禁止儲存 */ }
    document.documentElement.dataset.fjubacReducedMotion = preferences.reducedMotion ? "true" : "false";
  }, [preferences.reducedMotion]);

  const submitProfile = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); updateProfile.mutate({ name: profile.name, grade: profile.grade || undefined, contact: profile.contact || undefined }); };
  const submitPreferences = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); updatePreferences.mutate(preferences); };
  const submitPassword = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); changePassword.mutate({ currentPassword: String(form.get("currentPassword") || ""), newPassword: String(form.get("newPassword") || ""), confirmPassword: String(form.get("confirmPassword") || "") }); event.currentTarget.reset(); };
  const handleAvatar = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!["image/png", "image/jpeg", "image/webp"].includes(file.type)) return toast.error("頭像僅支援 PNG、JPEG 或 WebP。"); if (file.size > 2 * 1024 * 1024) return toast.error("頭像檔案上限為 2MB。"); const reader = new FileReader(); reader.onload = () => { if (typeof reader.result === "string") uploadAvatar.mutate({ dataUrl: reader.result }); }; reader.readAsDataURL(file); };

  if (!isAuthenticated) return <main className="workspace-gate"><LockKeyhole /><h1>個人中心需要登入</h1><p>請以已核准的社員帳號登入後，管理個人資料、帳號安全、個人偏好與可存取紀錄。</p><Link href="/account" className="club-primary">社員登入</Link></main>;
  if (summary.isLoading) return <main className="personal-loading"><LoaderCircle /><p>正在整理你的個人中心…</p></main>;
  if (summary.isError || !summary.data) return <main className="workspace-gate"><ShieldCheck /><h1>暫時無法載入個人中心</h1><p>{summary.error?.message || "請稍後再試。"}</p><button type="button" className="club-primary" onClick={() => summary.refetch()}>重新載入</button></main>;

  const data = summary.data;
  const initials = (data.user.name || data.user.email || "F").slice(0, 1).toUpperCase();
  return <main className="personal-shell">
    <header className="workspace-header"><Link href="/" className="back-link"><ArrowLeft size={16} />返回 FJUBAC</Link><div className="personal-header-actions"><Link href="/workspace"><FolderKanban size={16} />社員工作區</Link><button type="button" onClick={() => logout()}>登出</button></div></header>
    <section className="personal-hero"><div className="personal-avatar-wrap">{data.user.avatarUrl ? <img src={data.user.avatarUrl} alt="個人頭像" /> : <span>{initials}</span>}<label className="avatar-edit" title="更新個人頭像"><Camera size={16} /><input type="file" accept="image/png,image/jpeg,image/webp" onChange={handleAvatar} /></label></div><div><p className="club-section-number">MEMBER PROFILE</p><h1>{data.user.name || "我的個人中心"}</h1><p>管理只屬於你的個資、帳號安全、參與紀錄與偏好。所有工作範圍與資源權限會於後端再次確認。</p><div className="personal-identity-tags"><span>{data.user.accountType === "internal" ? "校內社員帳號" : "校外社員帳號"}</span><span>{statusLabel(data.user.accountStatus)}</span>{data.membership ? <span>社員資格：{statusLabel(data.membership.status)}</span> : null}</div></div></section>
    <nav className="personal-nav" aria-label="個人中心區塊"><a href="#profile">個資</a><a href="#security">帳號安全</a><a href="#activity">活動與任務</a><a href="#preferences">偏好</a><a href="#history">資源與異動</a></nav>
    <section className="personal-content"><section className="personal-overview"><article><UserRound size={17} /><span>社員資格</span><strong>{data.membership ? statusLabel(data.membership.status) : "尚無紀錄"}</strong><small>{data.membership?.joinedAt ? `加入於 ${formatDate(data.membership.joinedAt)}` : "資格依正式流程確認"}</small></article><article><ClipboardList size={17} /><span>我的待辦</span><strong>{myTasks.data?.length ?? 0}</strong><small>只計入尚未完成的實際任務</small></article><article><CalendarIcon size={17} /><span>活動報名</span><strong>{data.registrations.length}</strong><small>你的實際活動紀錄</small></article><article><Heart size={17} /><span>資源收藏</span><strong>{data.favorites.length}</strong><small>仍具讀取權限的收藏</small></article></section>
      <div className="personal-main-grid"><div className="personal-primary"><section id="profile" className="personal-panel"><header><div><UserRound /><div><p className="club-section-number">01 / PROFILE</p><h2>個人資料與頭像</h2></div></div></header><p>姓名、系級／年級與聯絡方式僅供已授權的本人與治理流程使用；Email 與學號不可在此自行改動。</p><form className="personal-form" onSubmit={submitProfile}><label>姓名<input required maxLength={100} value={profile.name} onChange={event => setProfile(current => ({ ...current, name: event.target.value }))} /></label><label>Email<input value={data.user.email || ""} disabled /></label><label>系級／年級<input maxLength={120} value={profile.grade} onChange={event => setProfile(current => ({ ...current, grade: event.target.value }))} /></label><label>聯絡方式<input maxLength={120} value={profile.contact} onChange={event => setProfile(current => ({ ...current, contact: event.target.value }))} /></label><button className="club-primary" disabled={updateProfile.isPending}>{updateProfile.isPending ? "儲存中…" : "儲存個人資料"}</button></form><p className="avatar-note"><ImagePlus size={15} />頭像僅接受 PNG、JPEG、WebP，檔案上限 2MB。{data.user.avatarUrl ? <button type="button" className="personal-text-action" onClick={() => removeAvatar.mutate()} disabled={removeAvatar.isPending}>移除目前頭像</button> : null}</p></section>
        <section id="security" className="personal-panel"><header><div><KeyRound /><div><p className="club-section-number">02 / SECURITY</p><h2>帳號與登入安全</h2></div></div></header><div className="security-facts"><span><Mail size={14} />{data.user.email || "Email 尚未提供"}</span><span><BadgeCheck size={14} />上次變更密碼：{formatDate(data.user.lastPasswordChangedAt)}</span><span><Activity size={14} />最近登入：{formatDate(data.user.lastSignedIn, true)}</span></div><form className="personal-form password-form" onSubmit={submitPassword}><label>目前密碼<input name="currentPassword" type="password" autoComplete="current-password" required /></label><label>新密碼<input name="newPassword" type="password" autoComplete="new-password" required /></label><label>確認新密碼<input name="confirmPassword" type="password" autoComplete="new-password" required /></label><button className="club-primary" disabled={changePassword.isPending}>{changePassword.isPending ? "更新中…" : "更新密碼"}</button></form></section>
        <section id="activity" className="personal-panel"><header><div><ClipboardList /><div><p className="club-section-number">03 / PARTICIPATION</p><h2>我的活動、專案與申請及任務</h2></div></div><Link href="/workspace" className="personal-text-action">前往工作區</Link></header><div className="personal-split-list"><div><h3>我的待辦</h3>{myTasks.isLoading ? <p>正在讀取實際待辦…</p> : myTasks.isError ? <p>暫時無法讀取待辦：{myTasks.error.message}</p> : myTasks.data?.length ? <ul>{myTasks.data.map(({ task, project }) => <li key={task.id}><strong>{task.title}</strong><span>{project.title} · {statusLabel(task.status)} · {task.dueAt ? `期限 ${formatDate(task.dueAt)}` : "未設定期限"}</span></li>)}</ul> : <p>目前沒有指派給你的實際待辦。</p>}</div><div><h3>近期活動</h3>{data.registrations.length ? <ul>{data.registrations.map(({ registration, event }) => <li key={registration.id}><strong>{event.title}</strong><span>{statusLabel(registration.status)} · {formatDate(event.startsAt, true)}</span>{["registered", "waitlisted"].includes(registration.status) ? <button type="button" className="personal-text-action" disabled={cancelRegistration.isPending} onClick={() => cancelRegistration.mutate({ eventId: event.id })}>取消報名</button> : null}</li>)}</ul> : <p>目前沒有你的活動報名紀錄。</p>}</div></div><div className="personal-split-list"><div><h3>有效專案</h3>{data.projects.length ? <ul>{data.projects.map(({ project, assignment }) => <li key={assignment.id}><strong>{project.title}</strong><span>{assignment.projectRole.replaceAll("_", " ")} · {statusLabel(project.status)}</span></li>)}</ul> : <p>目前沒有有效專案指派。</p>}</div><div><h3>申請追蹤</h3>{data.applications.length ? <ul>{data.applications.map(application => <li key={application.id}><strong>案件 #{application.id}</strong><span>{statusLabel(application.status)} · 更新於 {formatDate(application.updatedAt)}</span></li>)}</ul> : <p>目前帳號尚無可連結的申請案件。</p>}</div></div></section></div>
        <aside className="personal-sidebar"><section className="personal-panel compact"><header><div><UsersRound /><div><p className="club-section-number">ROLE & TERM</p><h2>我的資格與職務</h2></div></div></header>{data.assignments.length ? <ul className="role-list">{data.assignments.map(assignment => <li key={assignment.id}><strong>{assignment.title}</strong><span>{assignment.departmentName} · 至 {formatDate(assignment.endsOn)}</span></li>)}</ul> : <p>目前沒有有效幹部職務；社員資格與角色異動由正式治理流程管理。</p>}</section>
          <section className="personal-panel compact"><header><div><Bell /><div><p className="club-section-number">NOTIFICATIONS</p><h2>站內通知</h2></div></div></header>{data.notifications.length ? <ul className="notification-list">{data.notifications.map(notification => <li key={notification.id} className={notification.readAt ? "is-read" : ""}><div><strong>{notification.title}</strong>{notification.body ? <span>{notification.body}</span> : null}<small>{formatDate(notification.createdAt, true)}</small></div><div className="notification-actions">{notification.href ? <a href={notification.href} onClick={() => !notification.readAt && markNotificationRead.mutate({ notificationId: notification.id })}>查看</a> : null}{!notification.readAt ? <button type="button" onClick={() => markNotificationRead.mutate({ notificationId: notification.id })}>已讀</button> : null}<button type="button" aria-label={`封存 ${notification.title}`} onClick={() => archiveNotification.mutate({ notificationId: notification.id })}><Archive size={13} /></button></div></li>)}</ul> : <p>目前沒有實際站內通知。你的帳號、活動、專案或招生流程產生通知後才會在此顯示。</p>}</section>
          <section id="preferences" className="personal-panel compact"><header><div><SlidersHorizontal /><div><p className="club-section-number">PREFERENCES</p><h2>通知、隱私與動態</h2></div></div></header><form className="preference-form" onSubmit={submitPreferences}><label><input type="checkbox" checked={preferences.reducedMotion} onChange={event => setPreferences(current => ({ ...current, reducedMotion: event.target.checked }))} />減少非必要動畫</label><label><input type="checkbox" checked={preferences.inAppNotifications} onChange={event => setPreferences(current => ({ ...current, inAppNotifications: event.target.checked }))} />啟用站內通知偏好</label><label><input type="checkbox" checked={preferences.emailNotifications} onChange={event => setPreferences(current => ({ ...current, emailNotifications: event.target.checked }))} />同意 Email 通知（寄信服務啟用後生效）</label><label><input type="checkbox" checked={preferences.resourceHistoryVisible} onChange={event => setPreferences(current => ({ ...current, resourceHistoryVisible: event.target.checked }))} />在個人中心顯示資源存取紀錄</label><button type="submit" className="club-secondary" disabled={updatePreferences.isPending}>{updatePreferences.isPending ? "儲存中…" : "儲存偏好"}</button></form><p className="personal-help">通知只會在實際事件發生後建立；目前寄信服務尚未啟用。</p></section></aside></div>
      <section id="history" className="personal-history-grid"><section className="personal-panel"><header><div><NotebookTabs /><div><p className="club-section-number">04 / RESOURCE HISTORY</p><h2>我的資源存取紀錄</h2></div></div></header><p>僅記錄你實際按下「開啟」或「下載」的已授權資源。關閉偏好後，本頁不顯示歷程，但不影響必要稽核保存。</p>{preferences.resourceHistoryVisible ? data.resourceHistory.length ? <ul className="history-list">{data.resourceHistory.map(({ log, resource }) => <li key={log.id}><Eye size={15} /><div><strong>{resource.title}</strong><span>{log.action === "download" ? "下載" : "開啟"} · {resource.fileName} · {formatDate(log.createdAt, true)}</span></div></li>)}</ul> : <div className="history-empty">尚無資源存取紀錄。你可以前往社員工作區開啟或下載已授權資源。</div> : <div className="history-empty">你已選擇不在個人中心顯示資源存取紀錄。</div>}</section><section className="personal-panel"><header><div><Heart /><div><p className="club-section-number">FAVORITES</p><h2>我的資源收藏</h2></div></div><Link href="/workspace" className="personal-text-action">管理收藏</Link></header><p>只會顯示你目前仍有權讀取的資源。權限變更後，無法讀取的收藏不會在此頁出現。</p>{data.favorites.length ? <ul className="history-list">{data.favorites.map(({ favorite, resource }) => <li key={favorite.id}><Heart size={15} /><div><strong>{resource.title}</strong><span>{resource.fileName} · 收藏於 {formatDate(favorite.createdAt, true)}</span></div></li>)}</ul> : <div className="history-empty">尚無資源收藏。可在社員工作區將已授權資源加入收藏。</div>}</section><section className="personal-panel"><header><div><ShieldCheck /><div><p className="club-section-number">05 / ACCOUNT ACTIVITY</p><h2>個人異動／稽核摘要</h2></div></div></header><p>顯示與你帳號直接相關、且可向本人揭露的異動摘要；不顯示密碼、認證碼、他人個資或完整管理註記。</p>{data.auditSummary.length ? <ul className="history-list">{data.auditSummary.map(audit => <li key={audit.id}><CheckCircle2 size={15} /><div><strong>{auditLabel(audit.action)}</strong><span>{audit.source === "self" ? "本人操作" : "治理異動"} · {formatDate(audit.createdAt, true)}</span></div></li>)}</ul> : <div className="history-empty">目前沒有可顯示的個人異動摘要。</div>}</section></section>
    </section>
  </main>;
}

function CalendarIcon({ size }: { size?: number }) { return <ClipboardList size={size} />; }
