import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Check, ChevronLeft, Download, FileLock2, FileText, LoaderCircle, LockKeyhole, RotateCcw, Send } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useRoute } from "wouter";
import { toast } from "sonner";
import { AccessNotice } from "./ProjectListPage";

export default function ProjectDetailPage() {
  const [, params] = useRoute("/projects/:id"); const projectId = Number(params?.id);
  const { isAuthenticated, loading } = useAuth();
  const utils = trpc.useUtils();
  const [blocked, setBlocked] = useState(false); const [selectedStage, setSelectedStage] = useState<string>(); const [rollbackReason, setRollbackReason] = useState(""); const [newTitle, setNewTitle] = useState(""); const [newSummary, setNewSummary] = useState("");
  const query = trpc.workspace.projectWork.workflow.detail.useQuery({ projectId }, { enabled: isAuthenticated && !blocked && Number.isInteger(projectId) && projectId > 0, retry: false, refetchInterval: 15_000, refetchIntervalInBackground: false });
  useEffect(() => { if (query.isError && !blocked) setBlocked(true); }, [blocked, query.isError]);
  const refresh = () => utils.workspace.projectWork.workflow.detail.invalidate({ projectId });
  const transition = trpc.workspace.projectWork.workflow.transition.useMutation({ onSuccess: () => { toast.success("專案流程已更新，已通知有效專案成員。"); setRollbackReason(""); refresh(); }, onError: error => toast.error(error.message) });
  const createDocument = trpc.workspace.projectWork.workflow.documents.create.useMutation({ onSuccess: () => { toast.success("已建立階段文件紀錄。"); setNewTitle(""); setNewSummary(""); refresh(); }, onError: error => toast.error(error.message) });
  const exportDocuments = trpc.workspace.projectWork.workflow.exportStageDocuments.useMutation({ onSuccess: ({ files }) => { if (!files.length) { toast.info("此階段沒有可下載的已連結文件。"); return; } files.forEach((file, index) => window.setTimeout(() => { const link = document.createElement("a"); link.href = file.url; link.download = file.fileName; link.rel = "noreferrer"; document.body.appendChild(link); link.click(); link.remove(); }, index * 180)); toast.success(`已開始下載 ${files.length} 份階段文件。`); }, onError: error => toast.error(error.message) });
  if (!isAuthenticated || query.isError) return <AccessNotice login={!isAuthenticated} />;
  if (loading || query.isLoading || !query.data) return <main className="container py-20">正在載入專案流程…</main>;
  const { project, stages, state, documents, transitions, canManage } = query.data; const activeStage = selectedStage ?? state.currentStage; const currentIndex = stages.findIndex(stage => stage.key === state.currentStage); const viewedIndex = stages.findIndex(stage => stage.key === activeStage); const stageDocs = documents.filter(row => row.document.stage === activeStage);
  return <main className="container py-10 sm:py-14"><Link href="/projects" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-800 hover:text-blue-950"><ChevronLeft className="h-4 w-4" />返回專案列表</Link><section className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold tracking-[.16em] text-blue-700">PROJECT WORKFLOW</p><h1 className="mt-2 text-3xl font-bold text-slate-950 sm:text-4xl">{project.title}</h1><p className="mt-3 max-w-3xl leading-7 text-slate-700">{project.description || "此專案尚未提供對外說明。"}</p></div>{canManage && <Badge className="bg-blue-800">可管理流程</Badge>}</section>
    <Card className="mt-8 overflow-hidden border-blue-100"><CardHeader><CardTitle>八階段專案進度</CardTitle><CardDescription>選擇節點檢視對應文件。未獲管理授權者只會看見目前及先前已開放階段的有效文件。</CardDescription></CardHeader><CardContent><ol className="project-workflow-stepper" aria-label="專案流程階段">{stages.map((stage, index) => { const isFuture = index > currentIndex; const isCurrent = index === currentIndex; return <li key={stage.key}><button type="button" disabled={isFuture && !canManage} aria-current={isCurrent ? "step" : undefined} onClick={() => setSelectedStage(stage.key)} className={`project-workflow-step ${activeStage === stage.key ? "is-selected" : ""} ${isCurrent ? "is-current" : ""} ${isFuture ? "is-future" : ""}`}><span>{index < currentIndex ? <Check className="h-4 w-4" /> : index + 1}</span><strong>{stage.title}</strong></button></li>; })}</ol><div className="mt-6 flex justify-end border-t border-blue-100 pt-5"><Button variant="outline" onClick={() => exportDocuments.mutate({ projectId, stage: activeStage as never })} disabled={exportDocuments.isPending}><Download className="mr-2 h-4 w-4" />{exportDocuments.isPending ? "正在準備文件…" : "匯出該階段所有文件"}</Button></div></CardContent></Card>
    <section className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_20rem]"><Card className="border-blue-100"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>{stages[viewedIndex]?.title}</CardTitle><CardDescription className="mt-2">預期交付：{stages[viewedIndex]?.deliverables.join("、")}</CardDescription></div><Badge variant="secondary">{activeStage === state.currentStage ? "目前階段" : "已完成階段"}</Badge></div></CardHeader><CardContent>{stageDocs.length === 0 ? <p className="rounded-lg bg-slate-50 p-6 text-slate-700">此階段尚無可顯示文件。系統不會預填虛構的交付物、研究紀錄或檔案。</p> : <div className="space-y-3">{stageDocs.map(({ document, resource, deliverable }) => <article key={document.id} className={`rounded-lg border p-4 ${document.status === "locked" ? "border-amber-200 bg-amber-50" : "border-slate-200 bg-white"}`}><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-slate-950">{document.title}</h2>{document.summary && <p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{document.summary}</p>}</div>{document.status === "locked" && <Badge className="bg-amber-700"><FileLock2 className="mr-1 h-3 w-3" />已鎖定</Badge>}</div><p className="mt-3 text-xs text-slate-600">{resource ? `資源：${resource.title}` : "未連結資源"}{deliverable ? ` · 交付物：${deliverable.title}` : ""}</p></article>)}</div>}
      {canManage && <form className="mt-7 rounded-lg border border-dashed border-blue-200 bg-blue-50/60 p-5" onSubmit={event => { event.preventDefault(); if (!newTitle.trim()) return; createDocument.mutate({ projectId, stage: activeStage as never, title: newTitle.trim(), summary: newSummary.trim() || undefined }); }}><h2 className="font-semibold text-slate-950">新增此階段文件紀錄</h2><p className="mt-1 text-sm text-slate-700">僅建立真實文件的標題與摘要；可透過既有專案交付物／資源管理補上關聯。</p><div className="mt-4 grid gap-3"><Label>文件標題<Input value={newTitle} onChange={event => setNewTitle(event.target.value)} maxLength={200} required /></Label><Label>摘要（可選）<Textarea value={newSummary} onChange={event => setNewSummary(event.target.value)} maxLength={5000} /></Label><Button type="submit" disabled={createDocument.isPending}>{createDocument.isPending ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <FileText className="mr-2 h-4 w-4" />}新增文件紀錄</Button></div></form>}</CardContent></Card>
      <aside className="space-y-6"><Card className="border-blue-100"><CardHeader><CardTitle className="text-lg">流程操作</CardTitle></CardHeader><CardContent>{canManage ? <div className="space-y-4">{currentIndex < stages.length - 1 && <Button className="w-full" onClick={() => transition.mutate({ projectId, toStage: stages[currentIndex + 1].key })} disabled={transition.isPending}><Send className="mr-2 h-4 w-4" />前進至下一階段</Button>}<Label>退回原因（退回時必填）<Textarea value={rollbackReason} onChange={event => setRollbackReason(event.target.value)} maxLength={500} placeholder="請說明需要退回的原因" /></Label>{currentIndex > 0 && <div className="grid gap-2">{stages.slice(0, currentIndex).map(stage => <Button key={stage.key} variant="outline" onClick={() => transition.mutate({ projectId, toStage: stage.key, reason: rollbackReason })} disabled={transition.isPending || !rollbackReason.trim()}><RotateCcw className="mr-2 h-4 w-4" />退回至：{stage.title}</Button>)}</div>}<p className="text-xs leading-5 text-slate-600">退回會保留資料足跡，並鎖定後續階段仍為有效的文件。管理者可看見鎖定狀態，專案生不會取得鎖定內容。</p></div> : <p className="text-sm leading-6 text-slate-700">您可檢視被指派專案目前及先前階段的開放文件；流程異動由授權管理者執行。</p>}</CardContent></Card><Card className="border-blue-100"><CardHeader><CardTitle className="text-lg">最近異動</CardTitle></CardHeader><CardContent>{transitions.length === 0 ? <p className="text-sm text-slate-700">尚無流程異動紀錄。</p> : <ol className="space-y-3">{transitions.slice(0, 6).map(item => <li key={item.id} className="border-l-2 border-blue-200 pl-3 text-sm"><strong className="text-slate-900">{item.direction === "forward" ? "前進" : "退回"}</strong><p className="text-slate-700">至 {stages.find(stage => stage.key === item.toStage)?.title}</p>{item.reason && <p className="mt-1 text-slate-600">原因：{item.reason}</p>}</li>)}</ol>}</CardContent></Card></aside>
    </section></main>;
}
